spring:
  application:
    name: orch-service
server:
  port: 9002
  shutdown: graceful  #To enable graceful shutdown

---
spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s  #Allow graceful  timeout period


#Force Enable health probs. Would be enabled on kubernetes platform
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true  
    readinessstate:
      enabled: true
---
management:
  endpoints:
    web:
      exposure:
        include: "*"  health:    circuitbreakers:      enabled: true    ratelimiters:      enabled: true
#------------------
# http properties for rest Template Configuration
#------------------      
http:
  client:
    conn:
      time:
        to:
          live:
            minute: ${http_client_conn_time_to_live_minute:5000}
  conn:
    timeout: ${http_conn_timeout:3000}  
    request:
      timeout: ${http_conn_request_timeout:5000}  
    max:
      conn:
        perroute: ${http_client_max_conn_route:50}
        total: ${http_client_max_conn_total:100}
  evict:
    idle:
      conn:
        sec: ${http_evict_idle_conn:5}
  read:
    timeout: ${http_read_time_out:10000}

#------------------
# Thread Propertis
#------------------
gen:
  await:
    term:
      secs: ${gen_await_term_secs:5} 
  core:
    pool: 
      size: ${gen_core_pool_size:200}
  keep:
    alive: 
      seconds: ${gen_keep_alive_seconds:60}
  max:
    pool:
      size: ${gen_max_pool_size:300}
  queue: 
    capacity: ${gen_queue_capacity:100}
    
#--------------------------
#Resilience4j Properties
#http://localhost:9002/actuator/circuitbreakers
#http://localhost:9002/actuator/metrics/
#http://localhost:9002/actuator/metrics/{metric.name}
#-------------------------
resilience4j:
  circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: ${circuitbreaker_slidingWindowSize:100}
            minimum-number-of-calls: ${circuitbreaker_minimum-number-of-calls:2}
            permittedNumberOfCallsInHalfOpenState: ${circuitbreaker_permittedNumberOfCallsInHalfOpenState:3}
            waitDurationInOpenState: ${circuitbreaker_waitDurationInOpenState:30s}
            failureRateThreshold: ${circuitbreaker_failureRateThreshold:5}
            eventConsumerBufferSize: ${circuitbreaker_eventConsumerBufferSize:100}
            automatic-transition-from-open-to-half-open-enabled: true
            ignore-exceptions:
              - org.springframework.web.client.HttpClientErrorException
              
            
        someShared:
            slidingWindowSize: 50
            permittedNumberOfCallsInHalfOpenState: 10
    instances:
        events_actorid_repoid:
            baseConfig: default
            waitDurationInOpenState: 5000
        backendB:
            baseConfig: someShared
---           
resilience4j:  retry:    configs:      default:
        max-attempts: 10
        wait-duration: 100
        retry-exceptions:          - org.springframework.web.client.HttpClientErrorException
          - org.springframework.web.client.HttpServerErrorException
          - java.net.ConnectException
          - org.springframework.web.client.ResourceAccessException
    instances:      retry:
        base-config: default
        
  
#hazelcast:
 # mapName: testMap
  #Ttl:  120
  #maxIdle: 120
  
 